### ISSUE TITLE
Update lmdb to 0.9.17

### ISSUE THREAD

**Issue by fawick** [szferi/gomdb#38]
Are there any plans to upgrade the lmdb implementation to 0.9.17 or is this project essentially frozen?

**Comment by szferi** [comment]
Due to resource limitations, I would suggest you, look for other forks if you want more maintained version. Sorry.

**Comment by fawick** [comment]
Thanks, @szferi, for the quick answer! Any fork you can point out in particular as being well-maintained or at least broadly accepted?

**Comment by bmatsuo** [comment]
@fawick I am actively maintaining some bindings for LMDB (currently at 0.9.17) at [github.com/bmatsuo/lmdb-go/lmdb](https://godoc.org/github.com/bmatsuo/lmdb-go/lmdb). The API is a little different from gomdb. But it is structured to be a little more idiomatic and safer to use in general. And I've updated the cgo calling conventions to comply with the [restrictions](https://github.com/golang/go/issues/12416) dictated for go1.6.

Please consider it while you look for an alternative fork. I would love some more people to use the package and help get more real world testing in.

Cheers.

**Comment by fawick** [comment]
@bmatsuo Thank you very much, that is fantastic news. I have yet to start the project that I want to use LMDB in, so API differences between ldmb-go and gomdb are not a problem for me. On the contrary, I am going to be happy to use idiomatic Go.
